language: node_js
node_js:
  - 8.12.0
before_install:
  - openssl aes-256-cbc -K $encrypted_4629cddb74de_key -iv $encrypted_4629cddb74de_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 47.100.232.2\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
  - npm install
script:
  - npm run release
after_success:
  - npm prune --production
  - tar -zcvf learning.tar.bz2 *
  - scp learning.tar.bz2 ${REMOTE_SERVER}:~/
  - ssh ${REMOTE_SERVER} 'mkdir -p learning && tar -zxvf learning.tar.bz2 -C
    learning'
  - ssh ${REMOTE_SERVER} 'cd learning && npm install && npm run prd'
branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/songxingguo/learning.git
    - REMOTE_SERVER: root@47.100.232.2
